version: '3'
services:
  app:
    restart: always
    build:
      context: .
    volumes:
      - .:/app
    environment:
      # credentials編集時に使う
      - EDITOR=vim
      - RAILS_ENV=development
    command: rails s -b 0.0.0.0 -p 3000
    ports:
      - 3000:3000
